source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
   use_frameworks!

target 'LXLive' do

  # Pods for LXLive

#   pod 'Alamofire', '~> 4.3.0'
   pod 'Kingfisher'
   pod 'Moya', '~> 8.0.1'
   pod 'SwiftyJSON'

end
